version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  # comment out below to run in debug mode in IDE
#  api:
#    image: casestudy-myretail
#    ports:
#      - 8080:8080
#    links:
#      - mongo
